# Generated by Django 5.2.6 on 2025-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('account_count', models.IntegerField(default=0)),
                ('ins', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('fb', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('reply_comment_count', models.IntegerField(default=0)),
                ('reply_message_count', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日统计',
                'verbose_name_plural': '日统计',
                'ordering': ['-date'],
                'unique_together': {('date', 'owner_id')},
            },
        ),
    ]
