# Generated by Django 5.2.6 on 2025-09-19 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='动作名称，例如 user.activate / role.set_permissions', max_length=128)),
                ('target_type', models.CharField(help_text='目标对象类型，例如 user / role / permission', max_length=128)),
                ('target_id', models.CharField(blank=True, help_text='目标对象 ID，若无可留空', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='服务器记录时间（UTC）')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='发起请求的 IP 地址', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='发起请求的 User-Agent', max_length=512)),
                ('success', models.BooleanField(default=True, help_text='是否执行成功')),
                ('metadata', models.JSONField(blank=True, help_text='补充上下文信息（JSON）', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='执行该操作的管理员（可能为空，表示系统行为）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
