# Generated by Django 5.2.6 on 2025-09-19 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(choices=[('reply_comment', '回复评论'), ('reply_message', '回复消息'), ('post', '发帖')], help_text='使用场景', max_length=32)),
                ('name', models.CharField(help_text='配置名称', max_length=100)),
                ('content', models.TextField(help_text='提示词文本，支持变量')),
                ('variables', models.JSONField(default=list, help_text='允许的变量名列表')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='归属用户', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scene', 'name'],
            },
        ),
    ]
