# Generated by Django 5.2.6 on 2025-09-19 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', '发帖'), ('reply_comment', '回复评论')], max_length=32)),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('language', models.CharField(choices=[('auto', 'Auto'), ('zh', 'Chinese'), ('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='auto', help_text='AI 生成文案语言', max_length=8)),
                ('text', models.TextField(blank=True)),
                ('mentions', models.JSONField(default=list, help_text='可@的人用户名/ID 列表')),
                ('tags', models.JSONField(default=list, help_text='最多 5 个话题标签（字符串，不含#）')),
                ('payload', models.JSONField(default=dict, help_text='平台相关附加参数，如 comment_id 等')),
                ('last_status', models.CharField(default='new', help_text='new/success/partial/error', max_length=16)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.BooleanField(default=False, help_text='上次执行是否全部成功')),
                ('last_failed', models.BooleanField(default=False, help_text='上次执行是否存在失败')),
                ('last_text', models.TextField(blank=True, help_text='上次实际发送的最终文案（含 tags/mentions）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_tasks', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, help_text='执行所用提示词（系统内容）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='prompts.promptconfig')),
                ('selected_accounts', models.ManyToManyField(blank=True, related_name='simple_tasks', to='social.poolaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('type', models.CharField(choices=[('post', '发帖'), ('reply_comment', '回复评论')], max_length=32)),
                ('text', models.TextField(help_text='本次实际发送文案（含 tags/mentions）')),
                ('used_prompt', models.CharField(blank=True, max_length=200)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, help_text='平台返回的对象ID，如 tweet_id 或 post_id', max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='social.poolaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_task_runs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.simpletask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
