# Generated by Django 5.2.6 on 2025-09-08 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply_comment', '回复评论'), ('reply_message', '回复消息'), ('post', '发帖')], help_text='任务类型', max_length=32)),
                ('provider', models.CharField(help_text='平台，如 twitter/facebook/instagram', max_length=32)),
                ('social_config_id', models.IntegerField(blank=True, help_text='覆盖用社交配置ID（可选）', null=True)),
                ('ai_config_id', models.IntegerField(blank=True, help_text='覆盖用AI配置ID（可选）', null=True)),
                ('keyword_config_id', models.IntegerField(blank=True, help_text='关键词配置ID（可选）', null=True)),
                ('prompt_config_id', models.IntegerField(blank=True, help_text='提示词配置ID（可选）', null=True)),
                ('schedule', models.CharField(help_text='简单表达：cron/interval 文本，先占位', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('max_retries', models.IntegerField(default=3)),
                ('rate_limit_hint', models.CharField(blank=True, max_length=50)),
                ('payload_template', models.JSONField(default=dict, help_text='任务载荷模板（如发帖内容占位等）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='归属用户', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('request_dump', models.JSONField(blank=True, null=True)),
                ('response_dump', models.JSONField(blank=True, null=True)),
                ('affected_ids', models.JSONField(default=list)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.scheduledtask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
