# Generated by Django 5.2.6 on 2025-09-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', '发帖'), ('reply_comment', '回复评论')], max_length=32)),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('text', models.TextField(blank=True)),
                ('mentions', models.JSONField(default=list, help_text='可@的人用户名/ID 列表')),
                ('tags', models.JSONField(default=list, help_text='最多 5 个话题标签（字符串，不含#）')),
                ('payload', models.JSONField(default=dict, help_text='平台相关附加参数，如 comment_id 等')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_tasks', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, help_text='执行所用提示词（系统内容）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='prompts.promptconfig')),
                ('selected_accounts', models.ManyToManyField(blank=True, related_name='simple_tasks', to='social.poolaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
