# Generated by Django 5.2.6 on 2025-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='interval_minutes',
            field=models.IntegerField(default=5, help_text='执行间隔（分钟），优先于 schedule，运营直接填写整数'),
        ),
    ]
