# Generated by Django 5.2.6 on 2025-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='task_orig_id',
            field=models.CharField(blank=True, help_text='任务来源标识，如 Facebook 帖子 ID', max_length=64),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='task_remark',
            field=models.CharField(blank=True, help_text='备注信息', max_length=255),
        ),
    ]
