# Generated by Django 5.2.6 on 2025-10-10 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True, verbose_name='推文ID')),
                ('platform', models.CharField(max_length=100, verbose_name='平台名')),
                ('publish_count', models.IntegerField(default=0, verbose_name='发布数')),
                ('impression_count', models.IntegerField(default=0, verbose_name='曝光量(浏览量)')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数(私信预留)')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击量(前台预留)')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推文',
                'verbose_name_plural': '推文',
                'db_table': 't_tweets',
            },
        ),
        migrations.CreateModel(
            name='TweetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50, unique=True, verbose_name='评论ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('commenter_id', models.CharField(max_length=50, verbose_name='评论人ID')),
                ('commenter_nickname', models.CharField(max_length=100, verbose_name='评论人昵称')),
                ('reply_to_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='回复人ID')),
                ('reply_to_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='回复人昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.tweet', verbose_name='推文')),
            ],
            options={
                'verbose_name': '推文评论',
                'verbose_name_plural': '推文评论',
                'db_table': 't_tweet_comments',
                'indexes': [models.Index(fields=['tweet_id'], name='t_tweet_com_tweet_i_260e46_idx'), models.Index(fields=['commenter_id'], name='t_tweet_com_comment_6738cb_idx'), models.Index(fields=['created_at'], name='t_tweet_com_created_cf4be4_idx')],
            },
        ),
    ]
