# Generated by Django 5.2.6 on 2025-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='last_failed',
            field=models.BooleanField(default=False, help_text='上次执行是否存在失败'),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='last_status',
            field=models.CharField(default='new', help_text='new/success/partial/error', max_length=16),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='last_success',
            field=models.BooleanField(default=False, help_text='上次执行是否全部成功'),
        ),
    ]
