# Generated by Django 5.2.6 on 2025-10-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tweet_tweetcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='publish_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='article_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='文章ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='article_text',
            field=models.TextField(default=1, verbose_name='文章内容'),
            preserve_default=False,
        ),
    ]
