# Generated by Django 5.2.6 on 2025-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_simpletask_last_failed_simpletask_last_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='last_text',
            field=models.TextField(blank=True, help_text='上次实际发送的最终文案（含 tags/mentions）'),
        ),
    ]
