# Generated by Django 5.2.6 on 2025-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_scheduledtask_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='sla_seconds',
            field=models.IntegerField(blank=True, help_text='SLA 目标秒数（可选）', null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='ai_config_id_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='keyword_config_id_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='prompt_config_id_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='sla_met',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='social_config_id_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
