# Generated by Django 5.2.6 on 2025-09-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_simpletask_task_orig_id_simpletask_task_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpletask',
            name='task_orig_id',
        ),
    ]
