# Generated by Django 5.2.6 on 2025-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_scheduledtask_sla_seconds_taskrun_ai_config_id_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='interval_minutes',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='schedule',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='cron_expr',
            field=models.CharField(blank=True, help_text='Cron 表达式（当类型为 cron 时使用）', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text='月循环日期，1-31，支持负数代表倒数', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='结束生效时间（可选）', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='interval_value',
            field=models.IntegerField(blank=True, help_text='当类型为 minutely/hourly 时的间隔整数', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='recurrence_type',
            field=models.CharField(choices=[('once', '单次'), ('minutely', '每N分钟'), ('hourly', '每N小时'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('cron', 'Cron 表达式')], default='minutely', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='开始生效时间（可选）', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='执行时间（HH:MM），用于 daily/weekly/monthly', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='timezone',
            field=models.CharField(default='UTC', help_text='时区名称，如 Asia/Shanghai', max_length=64),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='weekday_mask',
            field=models.JSONField(blank=True, default=list, help_text='周循环选择，如 ["mon","tue"]，用于 weekly'),
        ),
    ]
