# Generated by Django 5.2.6 on 2025-09-13 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('tasks', '0003_simpletask_last_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('type', models.CharField(choices=[('post', '发帖'), ('reply_comment', '回复评论')], max_length=32)),
                ('text', models.TextField(help_text='本次实际发送文案（含 tags/mentions）')),
                ('used_prompt', models.CharField(blank=True, max_length=200)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, help_text='平台返回的对象ID，如 tweet_id 或 post_id', max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='social.poolaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_task_runs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.simpletask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
