# Generated by Django 5.2.6 on 2025-10-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tweet_created_date_remove_tweet_publish_count_and_more'),
    ]

    operations = [
        # 先重命名模型
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Article',
        ),
        # 再修改表名
        migrations.AlterModelTable(
            name='article',
            table='t_article',
        ),
        # 其余操作保持不变...
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50, unique=True, verbose_name='评论ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('commenter_id', models.CharField(max_length=50, verbose_name='评论人ID')),
                ('commenter_nickname', models.CharField(max_length=100, verbose_name='评论人昵称')),
                ('reply_to_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='回复人ID')),
                ('reply_to_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='回复人昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.article', verbose_name='推文')),
            ],
            options={
                'verbose_name': '推文评论',
                'verbose_name_plural': '推文评论',
                'db_table': 't_article_comments',
            },
        ),
        migrations.DeleteModel(
            name='TweetComment',
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article'], name='t_article_c_article_3c9498_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['commenter_id'], name='t_article_c_comment_70d492_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['created_at'], name='t_article_c_created_3530d1_idx'),
        ),
    ]
