# Generated by Django 5.2.6 on 2025-09-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_simpletaskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletask',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('zh', 'Chinese'), ('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='auto', help_text='AI 生成文案语言', max_length=8),
        ),
    ]
