# Generated by Django 5.2.6 on 2025-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_scheduledtask_interval_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
