# Generated by Django 5.2.6 on 2025-09-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskrun_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='external_object_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='rate_limit_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
