# Generated by Django 5.2.6 on 2025-09-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskrun_external_object_id_taskrun_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='ai_latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='ai_tokens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
