# Generated by Django 5.2.6 on 2025-09-10 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskrun_ai_latency_ms_taskrun_ai_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=32)),
                ('external_id', models.CharField(help_text='平台返回的对象ID', max_length=200)),
                ('text', models.TextField(blank=True, help_text='发布时的文本/说明')),
                ('payload', models.JSONField(blank=True, help_text='平台返回的完整数据结构', null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tasks.scheduledtask')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tasks.taskrun')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['provider', 'external_id'], name='tasks_socia_provide_483ccd_idx'), models.Index(fields=['owner'], name='tasks_socia_owner_i_422aee_idx')],
            },
        ),
    ]
