# Generated by Django 5.2.6 on 2025-09-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_socialpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='自动拼接的标签，如 #AI #新品', related_name='tasks', to='tasks.tag'),
        ),
    ]
