# Generated by Django 5.2.6 on 2025-09-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tag_scheduledtask_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_templates', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='templates', to='tasks.tag')),
            ],
            options={
                'ordering': ['owner_id', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='tag_template',
            field=models.ForeignKey(blank=True, help_text='可选：选择一个标签模板来自动附加标签', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='tasks.tagtemplate'),
        ),
    ]
