# Generated by Django 5.2.6 on 2025-09-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tagtemplate_scheduledtask_tag_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads')], max_length=32),
        ),
    ]
