# Generated by Django 5.2.6 on 2025-09-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_socialpost_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='tag_template',
        ),
        migrations.DeleteModel(
            name='TagTemplate',
        ),
    ]
