# Generated by Django 5.2.6 on 2025-09-11 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_socialaccount_external_user_id'),
        ('tasks', '0012_remove_scheduledtask_tag_template_delete_tagtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('external_user_id', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('manual', '手动录入'), ('imported', '同步导入')], default='manual', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='success', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('external_relation_id', models.CharField(blank=True, max_length=200)),
                ('response_dump', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_actions', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_actions', to='social.socialaccount')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tasks.followtarget')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='followtarget',
            index=models.Index(fields=['owner', 'provider'], name='tasks_follo_owner_i_d0d0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='followtarget',
            index=models.Index(fields=['provider', 'external_user_id'], name='tasks_follo_provide_993ff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followtarget',
            unique_together={('owner', 'provider', 'external_user_id')},
        ),
        migrations.AddIndex(
            model_name='followaction',
            index=models.Index(fields=['owner', 'provider'], name='tasks_follo_owner_i_f3716a_idx'),
        ),
        migrations.AddIndex(
            model_name='followaction',
            index=models.Index(fields=['provider', 'status'], name='tasks_follo_provide_40fc59_idx'),
        ),
        migrations.AddIndex(
            model_name='followaction',
            index=models.Index(fields=['executed_at'], name='tasks_follo_execute_b6039f_idx'),
        ),
    ]
