# Generated by Django 5.2.6 on 2025-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_followtarget_followaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='type',
            field=models.CharField(choices=[('reply_comment', '回复评论'), ('reply_message', '回复消息'), ('post', '发帖'), ('follow', '关注')], help_text='任务类型', max_length=32),
        ),
    ]
