# Generated by Django 5.2.6 on 2025-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_socialaccount_external_user_id'),
        ('tasks', '0014_alter_scheduledtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='runner_accounts',
            field=models.ManyToManyField(blank=True, help_text='执行用平台账号（多选）', related_name='runner_tasks', to='social.socialaccount'),
        ),
    ]
