# Generated by Django 5.2.6 on 2025-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_socialaccount_external_user_id'),
        ('tasks', '0015_scheduledtask_runner_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='runner_accounts',
        ),
        migrations.AddField(
            model_name='followtarget',
            name='runner_accounts',
            field=models.ManyToManyField(blank=True, help_text='对该目标执行关注操作的账号（多选）', related_name='follow_targets', to='social.socialaccount'),
        ),
    ]
