# Generated by Django 5.2.6 on 2025-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_scheduledtask_runner_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followtarget',
            name='completed',
            field=models.BooleanField(default=False, help_text='是否已完成任务（True 后不再作为候选）'),
        ),
    ]
