# Generated by Django 5.2.6 on 2025-09-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_followtarget_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='follow_daily_cap',
            field=models.IntegerField(blank=True, default=0, help_text='关注任务：当日成功关注上限（默认 0 表示不限；优先生效于 payload_template.daily_cap）', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='follow_max_per_run',
            field=models.IntegerField(blank=True, default=5, help_text='关注任务：每次最多处理的目标数量（默认 5；优先生效于 payload_template.max_per_run）', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='follow_targets',
            field=models.ManyToManyField(blank=True, help_text='关注任务：指定本任务要处理的目标清单（留空则按默认挑选）', related_name='scheduled_tasks', to='tasks.followtarget'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='payload_template',
            field=models.JSONField(default=dict, help_text='任务载荷模板（如发帖内容占位等；follow 类型不建议使用此处 target_ids 配置，改用字段）'),
        ),
    ]
