# Generated by Django 5.2.6 on 2025-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('access_token_secret', models.TextField(blank=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', help_text='active/inactive', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
    ]
