# Generated by Django 5.2.6 on 2025-09-08 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], help_text='社交平台', max_length=32)),
                ('name', models.CharField(help_text='配置名称', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='平台内是否默认（唯一）')),
                ('priority', models.IntegerField(default=0, help_text='平台内优先级，数值越大优先')),
                ('client_id', models.CharField(blank=True, help_text='客户端 ID / AppID', max_length=200)),
                ('client_secret', models.CharField(blank=True, help_text='客户端密钥 / AppSecret', max_length=300)),
                ('api_version', models.CharField(blank=True, help_text='API 版本（如 v19.0、2）', max_length=50)),
                ('redirect_uris', models.JSONField(default=list, help_text='回调 URI 列表')),
                ('scopes', models.JSONField(default=list, help_text='权限 scopes 列表')),
                ('bearer_token', models.CharField(blank=True, help_text='Twitter App-only Bearer Token', max_length=400)),
                ('app_id', models.CharField(blank=True, help_text='Facebook AppID（可与 client_id 同值）', max_length=200)),
                ('app_secret', models.CharField(blank=True, help_text='Facebook AppSecret（可与 client_secret 同值）', max_length=300)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID（可选）', max_length=200)),
                ('page_access_token', models.CharField(blank=True, help_text='Facebook Page Access Token（可选）', max_length=500)),
                ('ig_business_account_id', models.CharField(blank=True, help_text='Instagram 业务账号 ID（可选）', max_length=200)),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Webhook 验证 Token（可选）', max_length=200)),
                ('signing_secret', models.CharField(blank=True, help_text='签名校验密钥（可选）', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人（管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-is_default', '-priority', 'name'],
            },
        ),
    ]
