# Generated by Django 5.2.6 on 2025-09-19 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('access_token_secret', models.TextField(blank=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', help_text='active/inactive', max_length=32)),
                ('usage_policy', models.CharField(choices=[('limited', 'Limited (2 per day)'), ('unlimited', 'Unlimited')], default='unlimited', help_text='limited: 每天最多 2 次；unlimited: 不限次', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
    ]
