# Generated by Django 5.2.6 on 2025-09-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialconfig',
            options={'ordering': ['owner_id', 'provider', '-is_default', '-priority', 'name']},
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='归属用户（租户）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_platform_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
