# Generated by Django 5.2.6 on 2025-09-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolaccount',
            name='remark',
            field=models.CharField(blank=True, help_text='备注信息', max_length=255),
        ),
    ]
