# Generated by Django 5.2.6 on 2025-09-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_socialconfig_options_socialconfig_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], help_text='平台', max_length=32)),
                ('external_user_id', models.CharField(help_text='平台侧用户ID', max_length=200)),
                ('external_username', models.CharField(blank=True, help_text='平台侧用户名（可选）', max_length=200)),
                ('access_token', models.TextField(blank=True, help_text='访问令牌（后续加密存储）')),
                ('refresh_token', models.TextField(blank=True, help_text='刷新令牌（后续加密存储）')),
                ('expires_at', models.DateTimeField(blank=True, help_text='令牌过期时间', null=True)),
                ('scopes', models.JSONField(default=list, help_text='授权范围')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', help_text='凭据状态', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(blank=True, help_text='关联的应用配置（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='social.socialconfig')),
                ('owner', models.ForeignKey(help_text='归属用户（租户）', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '外部账号',
                'verbose_name_plural': '外部账号',
                'ordering': ['provider', 'external_username'],
                'indexes': [models.Index(fields=['provider', 'external_user_id'], name='social_soci_provide_5aea33_idx'), models.Index(fields=['owner'], name='social_soci_owner_i_577b04_idx')],
                'unique_together': {('provider', 'external_user_id', 'owner')},
            },
        ),
    ]
