# Generated by Django 5.2.6 on 2025-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='ban_reason',
            field=models.CharField(blank=True, help_text='封禁/异常原因（如有）', max_length=200),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='error_code',
            field=models.CharField(blank=True, help_text='最近错误码', max_length=64),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='failed_checks_count',
            field=models.IntegerField(default=0, help_text='连续失败次数'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='health_status',
            field=models.CharField(choices=[('active', 'Active'), ('warn', 'Warn'), ('banned', 'Banned'), ('unknown', 'Unknown')], default='unknown', help_text='健康状态', max_length=16),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='上次体检时间', null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, help_text='访问令牌（加密存储，开发可为明文）'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='刷新令牌（加密存储，开发可为明文）'),
        ),
    ]
