# Generated by Django 5.2.6 on 2025-09-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_socialaccount_ban_reason_socialaccount_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='平台侧用户ID', max_length=200),
        ),
    ]
