# Generated by Django 5.2.6 on 2025-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_socialaccount_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='external_user_id',
            field=models.CharField(blank=True, default='', help_text='平台侧用户ID', max_length=200),
        ),
    ]
