# Generated by Django 5.2.6 on 2025-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_socialaccount_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads')], help_text='平台', max_length=32),
        ),
        migrations.AlterField(
            model_name='socialconfig',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads')], help_text='社交平台', max_length=32),
        ),
    ]
