# Generated by Django 5.2.6 on 2025-09-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_socialaccount_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'external_user_id')},
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='归属用户（租户）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
