# Generated by Django 5.2.6 on 2025-09-12 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_socialaccount_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='平台侧用户ID', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_user_id__isnull', True), _negated=True), fields=('provider', 'external_user_id'), name='uniq_provider_external_user_id_not_null'),
        ),
    ]
