# Generated by Django 5.2.6 on 2025-09-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_socialaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='uniq_provider_external_user_id_not_null',
        ),
    ]
