# Generated by Django 5.2.6 on 2025-09-08 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, help_text='可选：平台过滤，如 twitter/facebook/instagram', max_length=32)),
                ('include_keywords', models.JSONField(default=list, help_text='包含关键词列表')),
                ('exclude_keywords', models.JSONField(default=list, help_text='排除关键词列表')),
                ('match_mode', models.CharField(choices=[('any', '匹配其中任意一个'), ('all', '匹配全部'), ('regex', '正则匹配')], default='any', help_text='匹配模式', max_length=10)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='归属用户', on_delete=django.db.models.deletion.CASCADE, related_name='keyword_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
