# Generated by Django 5.2.6 on 2025-09-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordconfig',
            name='name',
            field=models.CharField(blank=True, help_text='配置名称（可选）', max_length=100, null=True),
        ),
    ]
