# Generated by Django 5.2.6 on 2025-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconfig',
            options={'ordering': ['-is_default', '-priority', 'name']},
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='priority',
            field=models.IntegerField(default=0, help_text='优先级，数值越大优先'),
        ),
    ]
