# Generated by Django 5.2.6 on 2025-09-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiconfig_options_aiconfig_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('custom', 'Custom')], help_text='厂商', max_length=32),
        ),
    ]
